### ISSUE TITLE
[oneMKL][Sparse BLAS] Misleading missing text in dark mode in `set_matrix_property` page

### ISSUE THREAD

**Issue by gajanan-choudhary** [uxlfoundation/oneAPI-spec#588] opened 2024-09-25 23:26 UTC
The [`sparse::set_matrix_property` page in the oneMKL Specification](https://github.com/uxlfoundation/oneAPI-spec/blob/main/source/elements/oneMKL/source/domains/spblas/data_types/set_matrix_property.rst) appears to be rendered incorrectly in dark mode. See the [rendered HTML link](https://uxlfoundation.github.io/oneAPI-spec/spec/elements/oneMKL/source/domains/spblas/data_types/set_matrix_property.html#matrix-properties).

Here's the light mode view:
![image](https://github.com/user-attachments/assets/adc25efb-dd99-4650-be6c-6893aae4689d)

and here's the dark mode view:
![image](https://github.com/user-attachments/assets/0ca5ab6b-73e1-4d7e-a025-9859899717d4)

and here's the dark mode view with text selected (showing text is present, but just appears hidden, maybe the color is off?):
![image](https://github.com/user-attachments/assets/7dfe93ad-1d17-4f22-ab8f-ae35637c8c30)

**Comment by Rbiessy** [comment] 2024-09-26 09:23
Good catch, I didn't notice it. Pinging @rscohn2 since he mentioned he was planning to look into this kind of issues.

I can reproduce this issue locally. It looks like the issue is due to the new lines using `|` inside the table. I find it useful to describe the behavior of the property for each format. Maybe we should change this to have a subsection for every property (`symmetric`, `sorted`, etc) and inside a table for each format (`CSR`, `COO`, etc) if needed? That could make more sense once we support more matrices formats.

**Comment by Rbiessy** [comment] 2024-09-26 10:02
Note that I reported another issue directly to Robert. In the provisional spec the [Data handles](https://oneapi-spec.uxlfoundation.org/specifications/oneapi/v1.4-provisional-rev-1/elements/onemkl/source/domains/spblas/data_types/data_handles#) page does not have an arrow on the left to deploy the children pages like `init_dense_vector`. I can't reproduce that issue locally unfortunately.

**Comment by rscohn2** [comment] 2024-09-26 12:28
> In the provisional spec the [Data handles](https://oneapi-spec.uxlfoundation.org/specifications/oneapi/v1.4-provisional-rev-1/elements/onemkl/source/domains/spblas/data_types/data_handles#) page does not have an arrow on the left to deploy the children pages like init_dense_vector

It is controlled by https://github.com/uxlfoundation/oneAPI-spec/blob/6ad4cc5024236f455e9fa9bc00a7a110b8215694/source/index.rst?plain=1#L19

There is 1 extra level of nesting in the full spec versus onemkl standalone. I could make the full spec 4 so they render the same. Unlimited causes rendering problems.

I don't know what to do about the rendering problem in the table.

**Comment by Rbiessy** [comment] 2024-09-26 12:33
Thanks, increasing the maxdepth to 4 sounds good to me.

I'll just avoid the new lines in tables and push it in https://github.com/uxlfoundation/oneAPI-spec/pull/583

**Comment by Rbiessy** [comment] 2024-10-02 10:10
> There is 1 extra level of nesting in the full spec versus onemkl standalone. I could make the full spec 4 so they render the same. Unlimited causes rendering problems.

@rscohn2 just making sure, are you planning to look into this issue before the 1.4 spec is out?

**Comment by Rbiessy** [comment] 2024-10-23 09:11
The dark mode now renders correctly so closing this issue.
Created https://github.com/uxlfoundation/oneAPI-spec/issues/598 to continue the discussion with the navigation tree.

**Closed by Rbiessy** 2024-10-23 09:11 UTC
Labels: documentation, MKL
